import json

string = """feed_cat: 
17
parameter_cat: 
71
view_name: 
tables_interactive
view_display_id: 
page
view_args: 
view_path: 
content/table-as-fed
view_base_path: 
content/table-as-fed
view_dom_id: 
6742de9f896f0059ed03ea3b204d5d52
pager_element: 
0
ajax_html_ids[]: 
section3
ajax_html_ids[]: 
block-lang-dropdown-language
ajax_html_ids[]: 
lang_dropdown_form_language
ajax_html_ids[]: 
lang-dropdown-select-language_msddHolder
ajax_html_ids[]: 
lang-dropdown-select-language
ajax_html_ids[]: 
lang-dropdown-select-language_msdd
ajax_html_ids[]: 
lang-dropdown-select-language_title
ajax_html_ids[]: 
lang-dropdown-select-language_titleText
ajax_html_ids[]: 
lang-dropdown-select-language_child
ajax_html_ids[]: 
block-system-main-menu
ajax_html_ids[]: 
search-form
ajax_html_ids[]: 
edit-keys
ajax_html_ids[]: 
views-exposed-form-tables-interactive-page
ajax_html_ids[]: 
edit-feed-cat-wrapper
ajax_html_ids[]: 
edit-feed-cat
ajax_html_ids[]: 
edit-parameter-cat-wrapper
ajax_html_ids[]: 
edit-parameter-cat
ajax_html_ids[]: 
edit-submit-tables-interactive
ajax_html_ids[]: 
edit-reset
ajax_html_ids[]: 
section19
ajax_html_ids[]: 
block-block-6
ajax_html_ids[]: 
section2
ajax_html_ids[]: 
block-block-2
ajax_html_ids[]: 
block-menu-menu-footer-menu
ajax_html_ids[]: 
backtotop
ajax_html_ids[]: 
cboxOverlay
ajax_html_ids[]: 
colorbox
ajax_html_ids[]: 
cboxWrapper
ajax_html_ids[]: 
cboxTopLeft
ajax_html_ids[]: 
cboxTopCenter
ajax_html_ids[]: 
cboxTopRight
ajax_html_ids[]: 
cboxMiddleLeft
ajax_html_ids[]: 
cboxContent
ajax_html_ids[]: 
cboxTitle
ajax_html_ids[]: 
cboxCurrent
ajax_html_ids[]: 
cboxPrevious
ajax_html_ids[]: 
cboxNext
ajax_html_ids[]: 
cboxSlideshow
ajax_html_ids[]: 
cboxLoadingOverlay
ajax_html_ids[]: 
cboxLoadingGraphic
ajax_html_ids[]: 
cboxMiddleRight
ajax_html_ids[]: 
cboxBottomLeft
ajax_html_ids[]: 
cboxBottomCenter
ajax_html_ids[]: 
cboxBottomRight
ajax_page_state[theme]: 
FeedTablesTM09
ajax_page_state[theme_token]: 
7zX90RoAl-BnqypxDLXtj08I8J8uUZisF_XR0H1OX1A
ajax_page_state[css][modules/system/system.base.css]: 
1
ajax_page_state[css][modules/system/system.menus.css]: 
1
ajax_page_state[css][modules/system/system.messages.css]: 
1
ajax_page_state[css][modules/system/system.theme.css]: 
1
ajax_page_state[css][sites/all/libraries/chosen/chosen.css]: 
1
ajax_page_state[css][sites/all/modules/chosen/css/chosen-drupal.css]: 
1
ajax_page_state[css][sites/all/libraries/ms-Dropdown/css/msdropdown/dd.css]: 
1
ajax_page_state[css][modules/comment/comment.css]: 
1
ajax_page_state[css][modules/field/theme/field.css]: 
1
ajax_page_state[css][modules/node/node.css]: 
1
ajax_page_state[css][modules/search/search.css]: 
1
ajax_page_state[css][modules/user/user.css]: 
1
ajax_page_state[css][sites/all/modules/views/css/views.css]: 
1
ajax_page_state[css][sites/all/modules/back_to_top/css/back_to_top.css]: 
1
ajax_page_state[css][sites/all/modules/ckeditor/css/ckeditor.css]: 
1
ajax_page_state[css][sites/all/modules/colorbox/styles/default/colorbox_style.css]: 
1
ajax_page_state[css][sites/all/modules/ctools/css/ctools.css]: 
1
ajax_page_state[css][sites/all/modules/panels/css/panels.css]: 
1
ajax_page_state[css][//cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.css]: 
1
ajax_page_state[css][sites/all/modules/qtip/css/qtip.css]: 
1
ajax_page_state[css][sites/all/modules/lang_dropdown/msdropdown/css/msdropdown/ldsSkin.css]: 
1
ajax_page_state[css][sites/all/themes/FeedTablesTM09/css/system.menus.css]: 
1
ajax_page_state[css][sites/all/themes/FeedTablesTM09/css/system.theme.css]: 
1
ajax_page_state[js][0]: 
1
ajax_page_state[js][sites/all/modules/jquery_update/replace/jquery/1.7/jquery.min.js]: 
1
ajax_page_state[js][misc/jquery-extend-3.4.0.js]: 
1
ajax_page_state[js][misc/jquery-html-prefilter-3.5.0-backport.js]: 
1
ajax_page_state[js][misc/jquery.once.js]: 
1
ajax_page_state[js][misc/drupal.js]: 
1
ajax_page_state[js][sites/all/modules/jquery_update/replace/ui/ui/minified/jquery.ui.effect.min.js]: 
1
ajax_page_state[js][sites/all/modules/jquery_update/replace/ui/external/jquery.cookie.js]: 
1
ajax_page_state[js][sites/all/modules/jquery_update/replace/misc/jquery.form.min.js]: 
1
ajax_page_state[js][sites/all/libraries/chosen/chosen.jquery.min.js]: 
1
ajax_page_state[js][misc/ajax.js]: 
1
ajax_page_state[js][sites/all/modules/jquery_update/js/jquery_update.js]: 
1
ajax_page_state[js][sites/all/modules/back_to_top/js/back_to_top.js]: 
1
ajax_page_state[js][sites/all/libraries/colorbox/jquery.colorbox-min.js]: 
1
ajax_page_state[js][sites/all/modules/colorbox/js/colorbox.js]: 
1
ajax_page_state[js][sites/all/modules/colorbox/styles/default/colorbox_style.js]: 
1
ajax_page_state[js][//cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js]: 
1
ajax_page_state[js][sites/all/modules/custom_search/js/custom_search.js]: 
1
ajax_page_state[js][misc/tableheader.js]: 
1
ajax_page_state[js][sites/all/modules/views/js/base.js]: 
1
ajax_page_state[js][misc/progress.js]: 
1
ajax_page_state[js][sites/all/libraries/ms-Dropdown/js/msdropdown/jquery.dd.min.js]: 
1
ajax_page_state[js][sites/all/modules/views/js/ajax_view.js]: 
1
ajax_page_state[js][sites/all/modules/ctools/js/jump-menu.js]: 
1
ajax_page_state[js][misc/collapse.js]: 
1
ajax_page_state[js][misc/form.js]: 
1
ajax_page_state[js][sites/all/modules/google_analytics/googleanalytics.js]: 
1
ajax_page_state[js][sites/all/modules/lang_dropdown/lang_dropdown.js]: 
1
ajax_page_state[js][sites/all/modules/qtip/js/qtip.js]: 
1
ajax_page_state[js][sites/all/modules/chosen/chosen.js]: 
1
ajax_page_state[jquery_version]: 
1.7"""

lines = string.split("\n")
dictionary = {}

for i in range(len(lines)):
    if ": " in lines[i]:
        key = lines[i].split(": ")[0]
        value = None
        if ': ' not in lines[i+1]:
            value = lines[i+1]
            i += 1
        dictionary[key] = value

with open("body.json", "w") as f:
    json.dump(dictionary, f)
